# Generated by Django 3.2.7 on 2021-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/channel/image/'),
        ),
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
