# Generated by Django 3.2.7 on 2021-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='short_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
