# Generated by Django 3.2.7 on 2021-10-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210924_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(default='FILL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(upload_to='videos/channel/image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='videos.channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/video/file/'),
        ),
    ]
