# Generated by Django 3.2.7 on 2021-10-22 07:23

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staff_options'),
        ('videos', '0006_auto_20211022_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='favorite_by',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='favorite_channels', to='users.Profile'),
        ),
    ]
