# Generated by Django 3.2.7 on 2021-10-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_channel_favorite_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/video/thumbnail/'),
        ),
    ]
