# Generated by Django 3.2.7 on 2021-10-28 03:49

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='s3_base_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='videos/video/s3_base_file/'),
        ),
    ]
