# Generated by Django 3.2.7 on 2021-10-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_alter_video_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='short_end',
        ),
        migrations.RemoveField(
            model_name='video',
            name='short_start',
        ),
    ]
