# Generated by Django 3.2.7 on 2021-10-28 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20211028_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
