# Generated by Django 3.2.7 on 2021-11-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_video_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='aws_vibes_video_quality_convert_job_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='aws_vibes_video_quality_convert_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='aws_vibes_video_short_trimmer_job_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='aws_vibes_video_short_trimmer_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
