# Generated by Django 3.2.7 on 2021-11-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20211102_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='s3_base_file',
        ),
    ]
