# Generated by Django 3.2.7 on 2021-11-16 10:11

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_remove_video_s3_base_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processes'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processes'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
    ]
