# Generated by Django 3.2.7 on 2021-11-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_auto_20211116_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='creator',
            new_name='created_by',
        ),
    ]
