# Generated by Django 3.2.7 on 2021-11-16 10:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_auto_20211116_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
    ]
