# Generated by Django 3.2.7 on 2021-11-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20211116_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='publisher',
        ),
    ]
