# Generated by Django 3.2.7 on 2021-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_auto_20211116_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
