# Generated by Django 3.2.7 on 2021-11-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_auto_20211116_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_visible',
        ),
    ]
