# Generated by Django 3.2.7 on 2021-11-16 10:21

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_auto_20211116_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='date_process_failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_process_failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
    ]
