# Generated by Django 3.2.7 on 2021-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_auto_20211116_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
