# Generated by Django 3.2.7 on 2021-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_auto_20211116_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
