# Generated by Django 3.2.7 on 2021-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_auto_20211122_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='date_recreated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_recreated',
        ),
        migrations.AlterField(
            model_name='channel',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
