# Generated by Django 3.2.7 on 2021-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_auto_20211124_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/media_upload/file/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='videos/media_upload/file/')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
