# Generated by Django 3.2.7 on 2021-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='aws_vibes_video_transcript_job_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='aws_vibes_video_transcript_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
