# Generated by Django 3.2.7 on 2021-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staff_phone_number'),
        ('videos', '0032_auto_20211206_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to='users.Profile'),
        ),
    ]
