# Generated by Django 3.2.7 on 2021-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_video_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='aws_vibes_video_quality_convert_job_finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='aws_vibes_video_short_trimmer_job_finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='aws_vibes_video_transcript_job_finished',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
