# Generated by Django 3.2.7 on 2022-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_auto_20211210_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('index',)},
        ),
        migrations.AddField(
            model_name='channel',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='channels',
            field=models.ManyToManyField(related_name='channel_videos', to='videos.Channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
