# Generated by Django 3.2.7 on 2022-01-07 13:42

from django.db import migrations


def make_many_channels(apps, schema_editor):

    Video = apps.get_model('videos', 'Video')

    for video in Video.objects.all():
        video.channels.add(video.channel)


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_auto_20220107_1307'),
    ]

    operations = [
        migrations.RunPython(make_many_channels)
    ]
