# Generated by Django 3.2.7 on 2022-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0036_auto_20220107_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.AlterField(
            model_name='video',
            name='channels',
            field=models.ManyToManyField(related_name='videos', to='videos.Channel'),
        ),
    ]
