# Generated by Django 3.2.7 on 2022-01-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0037_auto_20220107_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('index', '-date_created')},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('index', '-date_created')},
        ),
    ]
