# Generated by Django 3.2.7 on 2022-01-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_auto_20220107_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='new',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
