# Generated by Django 3.2.7 on 2022-01-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_auto_20220120_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='index',
        ),
        migrations.RemoveField(
            model_name='video',
            name='index',
        ),
    ]
