# Generated by Django 3.2.7 on 2022-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0040_auto_20220120_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
