# Generated by Django 3.2.7 on 2022-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0041_video_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
