# Generated by Django 3.2.7 on 2022-01-20 20:30

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0043_auto_20220120_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
    ]
