# Generated by Django 3.2.7 on 2022-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0045_video_publish_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='publish_state',
        ),
    ]
