# Generated by Django 3.2.7 on 2022-01-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0047_auto_20220124_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='video',
            name='new',
        ),
    ]
