# Generated by Django 3.2.12 on 2022-02-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0048_auto_20220125_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='aws_vibes_video_quality_convert_job_finished',
            new_name='quality_convert_job_finished',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='aws_vibes_video_quality_convert_job_id',
            new_name='quality_convert_job_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='aws_vibes_video_short_trimmer_job_finished',
            new_name='short_trimmer_job_finished',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='aws_vibes_video_short_trimmer_job_id',
            new_name='short_trimmer_job_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='aws_vibes_video_transcript_job_finished',
            new_name='transcript_job_finished',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='aws_vibes_video_transcript_job_id',
            new_name='transcript_job_id',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='published_date',
        ),
    ]
