# Generated by Django 3.2.12 on 2022-03-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0049_auto_20220223_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_processed',
        ),
    ]
