# Generated by Django 3.2.12 on 2022-04-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0050_auto_20220310_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_by',
        ),
    ]
