# Generated by Django 3.2.12 on 2022-04-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0051_auto_20220409_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='processed_by',
        ),
    ]
