# Generated by Django 3.2.12 on 2022-04-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0052_auto_20220409_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_by',
        ),
    ]
