# Generated by Django 4.0.4 on 2022-04-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0054_auto_20220409_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='video',
            name='editor',
        ),
    ]
