# Generated by Django 4.0.4 on 2022-04-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0055_remove_channel_editor_remove_video_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_approved',
        ),
    ]
