# Generated by Django 4.0.4 on 2022-04-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0056_remove_channel_date_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_edited',
        ),
    ]
