# Generated by Django 4.0.4 on 2022-04-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0057_remove_channel_date_edited_remove_video_date_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_published',
        ),
    ]
