# Generated by Django 4.0.6 on 2022-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0058_remove_channel_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
