# Generated by Django 4.0.6 on 2022-08-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0059_video_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
