# Generated by Django 4.1 on 2022-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0060_channel_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="view_count_day",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="view_count_hour",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="view_count_total",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
