# Generated by Django 4.1.7 on 2023-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0062_initial_view_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='videos/creator/')),
                ('bio', models.TextField(blank=True)),
                ('is_staff_choice', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
