# Generated by Django 4.1.7 on 2023-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0064_video_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('order', '-date_created')},
        ),
        migrations.AddField(
            model_name='channel',
            name='is_staff_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
