# Generated by Django 4.1.7 on 2023-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0065_alter_channel_options_channel_is_staff_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='trend_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/video/trend/'),
        ),
    ]
