# Generated by Django 4.1.13 on 2023-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0066_video_is_favorite_video_is_trend_video_trend_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watch_count_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
