# Generated by Django 4.1.13 on 2024-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0067_video_watch_count_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='exclude_android',
            field=models.BooleanField(default=False),
        ),
    ]
