workflows:
  vibes-ios:
    name: iOS app
    instance_type: mac_mini_m1
    max_build_duration: 50
    working_directory: ./flutter
    integrations:
      app_store_connect: codemagic_vibes
    environment:
      flutter: &flutter_version 3.24.1
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.vibesonly.app
      vars:
        APP_STORE_ID: 1600518223
    cache:
      cache_paths:
      - ~/.pub-cache
    triggering:
      events:
      - push
      branch_patterns:
      - pattern: 'master'
        include: true
        source: true
      cancel_previous_builds: true
    when:
      changeset:
        includes:
        - 'flutter/'
        - 'flutter_mobile_app_presentation/'
        - 'codemagic.yaml'
    scripts:
    - &melos_bootstrap
      name: Melos Bootstrap
      script: |
        dart pub global activate melos
        melos bootstrap
    - &xcode_use_profiles
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles
    - &setup_prerequisites
      name: Setup local package dependencies.
      script: |
        melos run common:build_runner
        melos run mobile_app_presentation:intl
        melos run mobile_app_presentation:build_runner
    - &setup_app_proj
      name: Setup the "Vibes Only" app project
      script: |
        melos run vibes_only:build_runner
    - &analyze
      name: Run flutter analyzer
      script: |
        echo "Temporarily out of service."
    #          flutter analyze .
    - &install_pods
      name: Install pods
      script: |
        find . -name "Podfile" -execdir pod install \;
    - name: Flutter build ipa and automatic versioning
      script: |
        BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
        flutter build ipa --release --flavor production \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
    - build/ios/ipa/*.ipa
    - /tmp/xcodebuild_logs/*.log
    - flutter_drive.log
    publishing:
      email:
        recipients:
        - ashkan@6thsolution.com
        - amir@6thsolution.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
  vibes-ios-staging:
    name: (STAGING) iOS app
    instance_type: mac_mini_m1
    max_build_duration: 50
    working_directory: ./flutter
    integrations:
      app_store_connect: codemagic_vibes
    environment:
      flutter: *flutter_version
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.vibesonly.app.staging
      vars:
        APP_STORE_ID: 1635470639
    cache:
      cache_paths:
      - ~/.pub-cache
    triggering:
      events:
      - push
      branch_patterns:
      - pattern: 'master'
        include: true
        source: true
      cancel_previous_builds: true
    when:
      changeset:
        includes:
        - 'flutter/'
        - 'flutter_mobile_app_presentation/'
        - 'codemagic.yaml'
    scripts:
    - name: Install FlutterFire CLI
      script: |
        dart pub global activate flutterfire_cli
        export PATH="$PATH:$HOME/.pub-cache/bin"

    - *melos_bootstrap
    - *xcode_use_profiles
    - *setup_prerequisites
    - *setup_app_proj
    - *analyze
    - *install_pods
    - name: Flutter build ipa and automatic versioning
      script: |
        BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
        flutter build ipa --release --flavor staging \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
    - build/ios/ipa/*.ipa
    - /tmp/xcodebuild_logs/*.log
    - flutter_drive.log
    publishing:
      email:
        recipients:
        - ashkan@6thsolution.com
        - amir@6thsolution.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
