// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1Vjv8KkkXk_ZIz2pqOeHfsNFxtZ99_c',
    appId: '1:511710560633:android:fd7f004a3f20292e63efa8',
    messagingSenderId: '511710560633',
    projectId: 'vibes-only-fbb4c',
    databaseURL: 'https://vibes-only-fbb4c-default-rtdb.firebaseio.com',
    storageBucket: 'vibes-only-fbb4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDodUilyGmHl7I_G-Gf2_NOvSgdJpSb-c',
    appId: '1:511710560633:ios:102a500875e0484863efa8',
    messagingSenderId: '511710560633',
    projectId: 'vibes-only-fbb4c',
    databaseURL: 'https://vibes-only-fbb4c-default-rtdb.firebaseio.com',
    storageBucket: 'vibes-only-fbb4c.firebasestorage.app',
    androidClientId: '511710560633-0pq6n2a02li4s5vhefju6l6bac9h6upk.apps.googleusercontent.com',
    iosClientId: '511710560633-8rv2n2sboiahif3nst0ondh660ae4fo1.apps.googleusercontent.com',
    iosBundleId: 'com.vibesonly.app',
  );

}