// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingAppFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8XR3IaoWZkcYIE8gh9_I8HWiP06XAheM',
    appId: '1:753327348014:android:71d4de36056619f0f002bf',
    messagingSenderId: '753327348014',
    projectId: 'vibes-only---staging',
    databaseURL: 'https://vibes-only---staging-default-rtdb.firebaseio.com',
    storageBucket: 'vibes-only---staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKav02sp1K2xRgeOyDsv-0LIuQGicyBM',
    appId: '1:753327348014:ios:bae967a6eafeb102f002bf',
    messagingSenderId: '753327348014',
    projectId: 'vibes-only---staging',
    databaseURL: 'https://vibes-only---staging-default-rtdb.firebaseio.com',
    storageBucket: 'vibes-only---staging.firebasestorage.app',
    androidClientId: '753327348014-d5benel7m1so1gt8bc7jjofsfdvk0mbk.apps.googleusercontent.com',
    iosClientId: '753327348014-j4umgtmoh4hd9ntp16v49utsqu36toii.apps.googleusercontent.com',
    iosBundleId: 'com.vibesonly.app.staging',
  );

}