# Generated by Django 3.2.7 on 2022-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_number', models.CharField(max_length=15, null=True)),
                ('to', models.CharField(max_length=15, null=True)),
                ('body', models.TextField(null=True)),
                ('status_data', models.JSONField(blank=True, null=True)),
                ('send_data', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('receive', 'Receive'), ('send', 'Send')], max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
