# Generated by Django 3.2.7 on 2022-01-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliolog',
            name='type',
        ),
    ]
