# Generated by Django 3.2.12 on 2022-03-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0050_auto_20220310_1013'),
        ('log', '0003_awslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='awslog',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video'),
        ),
    ]
