# Generated by Django 3.2.12 on 2022-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_awslog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='awslog',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
