# Generated by Django 3.2.5 on 2021-09-09 15:16

from django.db import migrations, models
import hippo_shield.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            bases=(models.Model,),
            managers=[
                ('objects', hippo_shield.managers.UserManager()),
            ],
        ),
    ]
