# Generated by Django 3.2.5 on 2021-09-11 16:55

from django.conf import settings
import django.contrib.auth.hashers
from django.db import migrations, models
import django.db.models.deletion 
import uuid



class Migration(migrations.Migration):

    dependencies = [
        ('hippo_shield', '0002_auto_20210911_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPasswordAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_login', models.DateTimeField(blank=True, null=True)),
                ('date_logout', models.DateTimeField(blank=True, null=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('date_activated', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(default=django.contrib.auth.hashers.make_password, max_length=255)),
                ('date_password_changed', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_password_authentication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
