# Generated by Django 3.2.5 on 2021-09-13 17:51

from django.db import migrations, models
from hippo_shield.models import make_password


class Migration(migrations.Migration):

    dependencies = [
        ('hippo_shield', '0003_emailpasswordauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpasswordauthentication',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailpasswordauthentication',
            name='password',
            field=models.CharField(default=make_password, max_length=255),
        ),
    ]
