# Generated by Django 3.2.7 on 2021-09-20 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid



class Migration(migrations.Migration):

    dependencies = [
        ('hippo_shield', '0004_auto_20210913_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_login', models.DateTimeField(blank=True, null=True)),
                ('date_logout', models.DateTimeField(blank=True, null=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('date_activated', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_authentication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
