# Generated by Django 3.2.12 on 2022-03-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippo_shield', '0005_firebaseauthentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseAuthentication',
        ),
    ]
