# Generated by Django 3.2.12 on 2022-03-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippo_shield', '0006_delete_firebaseauthentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_use_django_admin',
        ),
    ]
