# Generated by Django 3.2.12 on 2022-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippo_shield', '0007_remove_user_can_use_django_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailpasswordauthentication',
            name='date_activated',
        ),
        migrations.RemoveField(
            model_name='emailpasswordauthentication',
            name='date_login',
        ),
        migrations.RemoveField(
            model_name='emailpasswordauthentication',
            name='date_logout',
        ),
        migrations.RemoveField(
            model_name='emailpasswordauthentication',
            name='date_used',
        ),
    ]
