# Generated by Django 3.2.7 on 2021-11-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0022_auto_20211028_0854'),
        ('users', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color_hex', models.CharField(blank=True, default='#7F00FF', max_length=255)),
                ('visual_draw', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Rhythm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_story_default', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhythms', to='stories.story')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ToyMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='studio.toy')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RhythmBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('intensity', models.IntegerField()),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.beat')),
                ('rhythm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='studio.rhythm')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='rhythm',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhythms', to='studio.toy'),
        ),
        migrations.AddField(
            model_name='beat',
            name='toy_motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='studio.toymotor'),
        ),
    ]
