# Generated by Django 3.2.7 on 2021-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toymotor',
            name='motor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
