# Generated by Django 3.2.7 on 2021-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_toymotor_motor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='pre_pattern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
