# Generated by Django 3.2.7 on 2021-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_beat_pre_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhythm',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
