# Generated by Django 3.2.7 on 2021-12-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_rhythm_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toy',
            new_name='Device',
        ),
    ]
