# Generated by Django 3.2.7 on 2021-12-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_toy_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToyMotor',
            new_name='DeviceMotor',
        ),
    ]
