# Generated by Django 3.2.7 on 2021-12-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_rename_toymotor_devicemotor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='toy_motor',
            new_name='device_motor',
        ),
        migrations.RenameField(
            model_name='devicemotor',
            old_name='toy',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='rhythm',
            old_name='toy',
            new_name='device',
        ),
    ]
