# Generated by Django 4.1.7 on 2023-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_auto_20211214_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='device',
            name='title',
        ),
        migrations.AddField(
            model_name='device',
            name='bluetooth_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='controller_page_picture',
            field=models.ImageField(blank=True, null=True, upload_to='studio/devices/'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_toy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='number_of_motors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='shop_picture',
            field=models.ImageField(blank=True, null=True, upload_to='studio/devices/'),
        ),
        migrations.AddField(
            model_name='device',
            name='shop_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
