# Generated by Django 4.1.7 on 2023-05-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_remove_device_date_created_remove_device_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemotor',
            name='device',
        ),
    ]
