# Generated by Django 4.1.7 on 2023-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_remove_devicemotor_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('ordering', '-created_at')},
        ),
        migrations.AddField(
            model_name='device',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
