# Generated by Django 4.1.7 on 2023-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_alter_device_options_device_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bluetooth_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
