# Generated by Django 4.1.7 on 2023-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_device_bluetooth_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='number_of_motors',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
