# Generated by Django 4.1.7 on 2023-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_alter_device_number_of_motors'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='motor_name1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='motor_name2',
            field=models.TextField(blank=True),
        ),
    ]
