# Generated by Django 3.2.7 on 2021-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.AddField(
            model_name='story',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_cover/'),
        ),
    ]
