# Generated by Django 3.2.7 on 2021-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210920_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_full/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_showcase_extended',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_extended/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_showcase_medium',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_medium/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_showcase_small',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_small/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_showcase_tall',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_tall/'),
        ),
    ]
