# Generated by Django 3.2.7 on 2021-09-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210920_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='beat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
