# Generated by Django 3.2.7 on 2021-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20210920_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('STAFF_PICKED', 'Staff Picked'), ('HOT_AND_NEW', 'Hot & New'), ('TRENDING', 'Trending')], default='STAFF_PICKED', max_length=255),
        ),
    ]
