# Generated by Django 3.2.7 on 2021-09-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stories', '0005_section_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_sections', to='users.staff'),
        ),
        migrations.AddField(
            model_name='section',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
