# Generated by Django 3.2.7 on 2021-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20210920_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'permissions': [('create_staff_picked', 'Can create staff picked section'), ('create_featured_content', 'Can create featured content section')]},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'permissions': [('edit_beats', 'Can add, edit & delete beat on stories'), ('edit_audios', 'Can add, edit & delete audio on stories')], 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('STAFF_PICKED', 'Staff Picked'), ('FEATURED_CONTENT', 'Featured Content'), ('HOT_AND_NEW', 'Hot & New'), ('TRENDING', 'Trending')], default='STAFF_PICKED', max_length=255),
        ),
    ]
