# Generated by Django 3.2.7 on 2021-09-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20210920_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='section',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='section',
            name='publisher',
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.home')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.section')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
