# Generated by Django 3.2.7 on 2021-09-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20210921_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionstory',
            options={'verbose_name_plural': 'Section stories'},
        ),
    ]
