# Generated by Django 3.2.7 on 2021-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_sectionstory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('STAFF_PICKED', 'Staff Picked'), ('FEATURED_CONTENT', 'Featured Content'), ('HOT_AND_NEW', 'Hot & New'), ('TRENDING', 'Trending'), ('CHARACTERS', 'Characters'), ('NEW_STORIES', 'New Stories'), ('TOP_CATEGORIES', 'Top Categories'), ('POPULAR_STORIES', 'Popular Stories'), ('RECENTLY_PLAYED', 'Recently Played')], default='STAFF_PICKED', max_length=255),
        ),
    ]
