# Generated by Django 3.2.7 on 2021-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_alter_section_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sections',
            field=models.ManyToManyField(blank=True, through='stories.HomeSection', to='stories.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='stories',
            field=models.ManyToManyField(blank=True, through='stories.SectionStory', to='stories.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories.Category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories.Character'),
        ),
    ]
