# Generated by Django 3.2.7 on 2021-10-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20211001_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionstory',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionstory',
            name='story',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='stories',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
        migrations.DeleteModel(
            name='SectionStory',
        ),
    ]
