# Generated by Django 3.2.7 on 2021-10-05 12:02

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_auto_20211005_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sections',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='stories.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='stories',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='stories.Story'),
        ),
    ]
