# Generated by Django 3.2.7 on 2021-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_auto_20211005_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
