# Generated by Django 3.2.7 on 2021-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_category_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
