# Generated by Django 3.2.7 on 2021-10-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_story_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(default='FILL', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(default='FILL', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='profile_image',
            field=models.ImageField(upload_to='stories/character/profile_image/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='style',
            field=models.CharField(default='SHOWCASE_SMALL', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='audio',
            field=models.FileField(upload_to='stories/story/audio/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(default='FILL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='image_cover',
            field=models.ImageField(upload_to='stories/story/image_cover/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_full',
            field=models.ImageField(upload_to='stories/story/image_full/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_extended',
            field=models.ImageField(upload_to='stories/story/image_showcase_extended/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_medium',
            field=models.ImageField(upload_to='stories/story/image_showcase_medium/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_small',
            field=models.ImageField(upload_to='stories/story/image_showcase_small/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_tall',
            field=models.ImageField(upload_to='stories/story/image_showcase_tall/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='short_description',
            field=models.TextField(default='FILL'),
            preserve_default=False,
        ),
    ]
