# Generated by Django 3.2.7 on 2021-10-22 05:38

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_auto_20211022_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='sections',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='homes', to='stories.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='stories',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='sections', to='stories.Story'),
        ),
    ]
