# Generated by Django 3.2.7 on 2021-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_story_favorite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='stories/story/audio/'),
        ),
    ]
