# Generated by Django 3.2.7 on 2021-11-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_auto_20211028_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_full/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_extended',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_extended/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_medium',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_medium/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_small',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_small/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_showcase_tall',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_showcase_tall/'),
        ),
    ]
