# Generated by Django 3.2.7 on 2021-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0023_auto_20211102_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='processed_image_cover',
            field=models.ImageField(
                blank=True, null=True, upload_to='stories/story/processed_image_cover/'
            ),
        ),
    ]
