# Generated by Django 3.2.7 on 2021-11-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_story_processed_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='processed_image_full',
            field=models.ImageField(
                blank=True, null=True, upload_to='stories/story/processed_image_full/'
            ),
        ),
        migrations.AddField(
            model_name='story',
            name='processed_image_showcase_extended',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='stories/story/processed_image_showcase_extended/',
            ),
        ),
        migrations.AddField(
            model_name='story',
            name='processed_image_showcase_medium',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='stories/story/processed_image_showcase_medium/',
            ),
        ),
        migrations.AddField(
            model_name='story',
            name='processed_image_showcase_small',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='stories/story/processed_image_showcase_small/',
            ),
        ),
        migrations.AddField(
            model_name='story',
            name='processed_image_showcase_tall',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='stories/story/processed_image_showcase_tall/',
            ),
        ),
    ]
