# Generated by Django 3.2.7 on 2021-11-03 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_auto_20211102_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_length_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='transcript_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
