# Generated by Django 3.2.7 on 2021-11-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_auto_20211116_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='creator',
            new_name='created_by',
        ),
    ]
