# Generated by Django 3.2.7 on 2021-11-16 10:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0029_auto_20211116_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
    ]
