# Generated by Django 3.2.7 on 2021-11-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0031_auto_20211116_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='character',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='home',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='section',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='story',
            name='publisher',
        ),
    ]
