# Generated by Django 3.2.7 on 2021-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0032_auto_20211116_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
