# Generated by Django 3.2.7 on 2021-11-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0033_auto_20211116_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='home',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_visible',
        ),
    ]
