# Generated by Django 3.2.7 on 2021-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0035_auto_20211116_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='date_process_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
