# Generated by Django 3.2.7 on 2021-11-16 12:34

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0036_auto_20211116_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50, protected=True),
        ),
    ]
