# Generated by Django 3.2.7 on 2021-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0037_auto_20211116_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='date_recreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
