# Generated by Django 3.2.7 on 2021-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0038_auto_20211122_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_recreated',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_recreated',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_recreated',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_recreated',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_recreated',
        ),
        migrations.AlterField(
            model_name='category',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
