# Generated by Django 3.2.7 on 2021-12-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0040_auto_20211124_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/character/profile_image/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='stories/story/image_cover/'),
        ),
    ]
