# Generated by Django 3.2.7 on 2022-01-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0042_auto_20220119_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
