# Generated by Django 3.2.7 on 2022-01-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0043_auto_20220119_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='new',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='staff_pick',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='top_10',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='trending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
