# Generated by Django 3.2.7 on 2022-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0044_auto_20220119_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='show_on_homepage',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
