# Generated by Django 3.2.7 on 2022-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0045_character_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
