# Generated by Django 3.2.7 on 2022-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0046_story_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
