# Generated by Django 3.2.7 on 2022-01-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0049_auto_20220120_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='publish_state',
            field=models.CharField(choices=[('simulation', 'simulation'), ('production', 'production')], default='simulation', max_length=10),
        ),
    ]
