# Generated by Django 3.2.7 on 2022-01-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0050_story_publish_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='publish_state',
            field=models.CharField(choices=[('simulation', 'simulation'), ('production', 'production')], default='simulation', max_length=10),
        ),
    ]
