# Generated by Django 3.2.7 on 2022-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0052_category_publish_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publish_state',
        ),
        migrations.RemoveField(
            model_name='character',
            name='publish_state',
        ),
        migrations.RemoveField(
            model_name='story',
            name='publish_state',
        ),
    ]
