# Generated by Django 3.2.7 on 2022-01-24 20:05

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0053_auto_20220122_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('STAFF_PICKED', 'Staff Picked'), ('FEATURED_CONTENT', 'Featured Content'), ('TRENDING', 'Trending'), ('NEW_STORIES', 'New Stories'), ('POPULAR_STORIES', 'Popular Stories'), ('RECENTLY_PLAYED', 'Recently Played'), ('CHARACTERS', 'Characters'), ('TOP_CATEGORIES', 'Top Categories')], default='STAFF_PICKED', max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('processed', 'Processed'), ('processing', 'Processing'), ('process_failed', 'Process Failed'), ('approved', 'Approved'), ('published', 'Published')], default='created', max_length=50),
        ),
    ]
