# Generated by Django 3.2.7 on 2022-01-24 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0054_auto_20220124_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
