# Generated by Django 3.2.12 on 2022-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0055_alter_story_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_processing_is_done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
