# Generated by Django 3.2.12 on 2022-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0056_story_image_processing_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_processing_is_done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
