# Generated by Django 3.2.12 on 2022-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0057_story_audio_processing_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audio_processing_is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_processing_is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
