# Generated by Django 3.2.12 on 2022-02-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0058_auto_20220221_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='processed_image_cover',
        ),
        migrations.RemoveField(
            model_name='story',
            name='processed_image_full',
        ),
        migrations.RemoveField(
            model_name='story',
            name='processed_image_showcase_extended',
        ),
        migrations.RemoveField(
            model_name='story',
            name='processed_image_showcase_medium',
        ),
        migrations.RemoveField(
            model_name='story',
            name='processed_image_showcase_small',
        ),
        migrations.RemoveField(
            model_name='story',
            name='processed_image_showcase_tall',
        ),
    ]
