# Generated by Django 3.2.12 on 2022-03-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0059_auto_20220223_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_process_failed',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_process_started',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_processed',
        ),
    ]
