# Generated by Django 3.2.12 on 2022-03-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0060_auto_20220310_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
    ]
