# Generated by Django 3.2.12 on 2022-04-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0061_alter_section_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='home',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_by',
        ),
    ]
