# Generated by Django 3.2.12 on 2022-04-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0062_auto_20220409_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='home',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='processed_by',
        ),
    ]
