# Generated by Django 3.2.12 on 2022-04-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0063_auto_20220409_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='home',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='home',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='published_by',
        ),
    ]
