# Generated by Django 4.0.4 on 2022-04-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0065_auto_20220409_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='character',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='home',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='story',
            name='editor',
        ),
    ]
