# Generated by Django 4.0.4 on 2022-04-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0066_remove_category_editor_remove_character_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_approved',
        ),
    ]
