# Generated by Django 4.0.4 on 2022-04-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0067_remove_category_date_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_edited',
        ),
    ]
