# Generated by Django 4.0.4 on 2022-04-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0068_remove_category_date_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_published',
        ),
    ]
