# Generated by Django 4.0.6 on 2022-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0069_remove_category_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
