# Generated by Django 4.0.6 on 2022-08-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0070_story_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
