# Generated by Django 4.1 on 2022-08-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0071_category_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="view_count_day",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="view_count_hour",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="view_count_total",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
