# Generated by Django 4.1 on 2022-09-07 10:25

from django.db import migrations


def update_initial_view_counts(apps, schema_editor):
    Story = apps.get_model("stories", "Story")
    Story.objects.filter(pk=15).update(view_count_total=2609)
    Story.objects.filter(pk=16).update(view_count_total=942)
    Story.objects.filter(pk=19).update(view_count_total=1372)
    Story.objects.filter(pk=20).update(view_count_total=819)
    Story.objects.filter(pk=21).update(view_count_total=717)
    Story.objects.filter(pk=23).update(view_count_total=1879)
    Story.objects.filter(pk=24).update(view_count_total=431)
    Story.objects.filter(pk=25).update(view_count_total=4563)
    Story.objects.filter(pk=29).update(view_count_total=2572)
    Story.objects.filter(pk=31).update(view_count_total=788)
    Story.objects.filter(pk=32).update(view_count_total=1433)
    Story.objects.filter(pk=33).update(view_count_total=1329)
    Story.objects.filter(pk=34).update(view_count_total=837)
    Story.objects.filter(pk=35).update(view_count_total=3619)
    Story.objects.filter(pk=36).update(view_count_total=1710)
    Story.objects.filter(pk=37).update(view_count_total=1714)
    Story.objects.filter(pk=38).update(view_count_total=2119)
    Story.objects.filter(pk=39).update(view_count_total=1899)
    Story.objects.filter(pk=40).update(view_count_total=1161)
    Story.objects.filter(pk=41).update(view_count_total=1934)
    Story.objects.filter(pk=43).update(view_count_total=1233)
    Story.objects.filter(pk=44).update(view_count_total=1371)
    Story.objects.filter(pk=45).update(view_count_total=2123)
    Story.objects.filter(pk=46).update(view_count_total=2038)
    Story.objects.filter(pk=47).update(view_count_total=2022)
    Story.objects.filter(pk=48).update(view_count_total=1830)
    Story.objects.filter(pk=49).update(view_count_total=1466)
    Story.objects.filter(pk=50).update(view_count_total=704)
    Story.objects.filter(pk=51).update(view_count_total=2088)
    Story.objects.filter(pk=52).update(view_count_total=1121)
    Story.objects.filter(pk=53).update(view_count_total=2372)
    Story.objects.filter(pk=54).update(view_count_total=3915)
    Story.objects.filter(pk=55).update(view_count_total=1511)
    Story.objects.filter(pk=56).update(view_count_total=1781)


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0072_story_view_count_day_story_view_count_hour_and_more"),
    ]

    operations = [migrations.RunPython(update_initial_view_counts)]
