# Generated by Django 4.1.5 on 2023-01-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0073_initial_view_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="audio_preview",
            field=models.FileField(blank=True, null=True, upload_to="preview/"),
        ),
    ]
