# Generated by Django 4.1.5 on 2023-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0074_story_audio_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ("order", "id")},
        ),
        migrations.AddField(
            model_name="character",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
