# Generated by Django 4.1.13 on 2024-01-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0075_alter_character_options_character_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='android_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/category/image/android/'),
        ),
    ]
