# Generated by Django 3.2.7 on 2021-09-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('crud_story', 'Stories'), ('crud_category', 'Categories'), ('crud_character', 'Characters'), ('crud_channel', 'Channels'), ('crud_video', 'Videos'), ('crud_staff', 'User Management'), ('update_beat', 'Beats'), ('create_staff_picked', 'Staff Picked Content'), ('create_featured_content', 'Featured Content'), ('create_home', 'Home Page'), ('update_audio', 'Staff Picked Content')]},
        ),
    ]
