# Generated by Django 3.2.7 on 2021-12-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('editor', 'Editor'), ('simulator', 'Simulator'), ('publisher', 'Publisher')]},
        ),
    ]
