# Generated by Django 3.2.7 on 2021-12-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
