# Generated by Django 3.2.7 on 2022-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pushmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='fcm_message_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
