# Generated by Django 3.2.7 on 2022-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220121_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_code_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
