# Generated by Django 3.2.7 on 2022-01-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login_code_expire_at',
        ),
    ]
