# Generated by Django 3.2.7 on 2022-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220121_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_fa_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
