# Generated by Django 3.2.7 on 2022-01-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_two_fa_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
