# Generated by Django 3.2.12 on 2022-03-04 19:25

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.profile_image_path),
        ),
    ]
