# Generated by Django 4.0.4 on 2022-04-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('simulator', 'Simulator'), ('publisher', 'Publisher')]},
        ),
    ]
