# Generated by Django 4.0.6 on 2022-07-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_staff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
