# Generated by Django 4.0.6 on 2022-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_pushmessage_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='target',
            field=models.CharField(choices=[('all', 'All'), ('free', 'Free'), ('paid', 'Paid')], default='all', max_length=31),
        ),
    ]
