# Generated by Django 4.1.7 on 2023-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_pushmessage_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=15),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='task_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
