# Generated by Django 4.1.9 on 2023-06-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_pushmessage_scheduled_for_pushmessage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=15),
        ),
    ]
