# Generated by Django 3.2.11 on 2022-02-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=1024)),
                ('subscription_id', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
