# Generated by Django 3.2.11 on 2022-02-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='device_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
