# Generated by Django 3.2.11 on 2022-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_subscription_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(max_length=20480),
        ),
    ]
