# Generated by Django 4.0.4 on 2022-04-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_subscription_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(max_length=40480),
        ),
    ]
