# Generated by Django 4.0.6 on 2022-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_subscription_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='app_platform',
            field=models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=8, null=True),
        ),
    ]
