# Generated by Django 4.1.7 on 2023-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_subscription_app_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True)),
                ('code', models.CharField(max_length=32)),
                ('target', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=32)),
                ('subscription_type', models.CharField(blank=True, choices=[('monthly_billing', 'Monthly'), ('annual_billing', 'Annual')], max_length=32, null=True)),
                ('days_since_membership_start', models.PositiveIntegerField(blank=True, null=True)),
                ('days_until_subscription_end', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
