# Generated by Django 4.1.7 on 2023-05-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='days_since_membership_start_constraint',
            field=models.CharField(choices=[('equals', 'Equals'), ('less_than', 'Less Than'), ('more_than', 'More Than')], default='more_than', max_length=32),
        ),
        migrations.AddField(
            model_name='promotion',
            name='days_since_registration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='days_since_registration_constraint',
            field=models.CharField(choices=[('equals', 'Equals'), ('less_than', 'Less Than'), ('more_than', 'More Than')], default='more_than', max_length=32),
        ),
        migrations.AddField(
            model_name='promotion',
            name='days_until_subscription_end_constraint',
            field=models.CharField(choices=[('equals', 'Equals'), ('less_than', 'Less Than'), ('more_than', 'More Than')], default='more_than', max_length=32),
        ),
        migrations.AddField(
            model_name='promotion',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='Number of times to show this promotion'),
        ),
    ]
