# Generated by Django 4.1.7 on 2023-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_promotion_days_since_membership_start_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=4096),
        ),
    ]
