# Generated by Django 4.1.7 on 2023-09-12 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='visit_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
