from django.conf import settings


_HIT_COUNT_SETTINGS = getattr(settings, "HIT_COUNT", {})

DEFAULT_CACHE_KEY_PREFIX = "_hit_count"
DEFAULT_CACHE_KEY_SEPARATOR = ":"


CACHE_KEY_PREFIX = _HIT_COUNT_SETTINGS.get(
    "CACHE_KEY_PREFIX",
    DEFAULT_CACHE_KEY_PREFIX,
)
CACHE_KEY_SEPARATOR = _HIT_COUNT_SETTINGS.get(
    "CACHE_KEY_SEPARATOR",
    DEFAULT_CACHE_KEY_SEPARATOR,
)

REDIS_URL = _HIT_COUNT_SETTINGS.get("REDIS_URL")
REDIS_DB = _HIT_COUNT_SETTINGS.get("REDIS_DB", 0)

TIME_ZONE = _HIT_COUNT_SETTINGS.get("TIME_ZONE", "UTC")

URLS = _HIT_COUNT_SETTINGS.get("URLS", {})

